attempt to add python function decoder
losttech/pythonnet pull request #1
Opened 2020-01-30 23:18 UTC by koubaa

Adds a python action decoder to your branch
Theres' a lot more work here to do to really make this fully featured but I wanted to submit the PR here while your branch hasn't yet been merged into pythonnet/pythonnet for feedback.

2020-01-31 19:49 UTC, lostmsu requested changes
Of course this needs generics handling to be accepted here or in upstream (or rather any delegate type handling). But looks good for singular use.

2020-01-31 19:49 UTC, lostmsu commented on src/runtime/Codecs/FunctionCodec.cs
> +            var args = targetType.GetGenericArguments();
Before trying anything else, you should check if your codec actually supports `targetType` too.

2020-01-31 19:49 UTC, lostmsu commented on src/runtime/Codecs/FunctionCodec.cs
> +            Action action = () =>
Here I'd also check if `T` is `Action` before doing anything else.

2020-02-01 22:10 UTC, koubaa commented
@lostmsu generics are hard, especially since I don't have much experience with them in C# (I'm much more familiar with c++).  Anyways I am trying out your suggestions.  Right now the hardest part is determining how many arguments for System.Action to use in TryDecode.  I think each argument has to be "object" because python functions don't care about the type.  I'm ignoring **kwargs for now

2020-02-02 03:05 UTC, lostmsu commented
@koubaa you might want to check this out: https://stackoverflow.com/questions/429552/can-i-get-the-signature-of-a-c-sharp-delegate-by-its-type

2020-03-03 21:39 UTC, lostmsu commented
Closing this, as Codecs are now in upstream.

2020-03-03 21:39 UTC, closed without merging